# Generated by Django 2.0.1 on 2018-02-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='styurl2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='소개이미지2'),
        ),
        migrations.AlterField(
            model_name='play',
            name='styurl3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='소개이미지3'),
        ),
        migrations.AlterField(
            model_name='play',
            name='styurl4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='소개이미지4'),
        ),
    ]
