# Generated by Django 2.0.1 on 2018-02-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupprofile',
            name='groupuser',
        ),
        migrations.AddField(
            model_name='profile',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/%Y/%m/%d', verbose_name='극단사진 giveme'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_groupuser',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='GroupProfile',
        ),
    ]
