# Generated by Django 2.0.1 on 2018-02-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180215_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_groupuser',
            field=models.BooleanField(),
        ),
    ]
