# Generated by Django 2.0.1 on 2018-02-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180215_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_groupuser',
            field=models.BooleanField(default=False),
        ),
    ]
