# Generated by Django 2.0.1 on 2018-02-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180215_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='liebe_a',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='liebe_t',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='recommand_t',
        ),
    ]
