# Generated by Django 2.0.1 on 2018-02-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180219_1134'),
        ('accounts', '0006_auto_20180218_2159'),
    ]

    operations = [
    ]
