# Generated by Django 2.0.1 on 2018-02-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20180220_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liebe_a',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='좋아하는 배우는요? 딱 한사람만 말하셔야 되용ㅎㅎ 프로그램을 그따구로 해서 ㅋㅋㅋ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='liebe_t',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='당신의 가장 좋아하는 연극 하나만!! 알려주세욯ㅎ??'),
        ),
        migrations.AddField(
            model_name='profile',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='선호가격'),
        ),
        migrations.AddField(
            model_name='profile',
            name='recommand_t',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='짧은 자기 소개!'),
        ),
    ]
