# Generated by Django 2.0.1 on 2018-02-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_recommand_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liebe_a',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='좋아하는 배우는요? 딱 한사람만 말하셔야 되용ㅎㅎ 프로그램을 그따구로 해서 ㅋㅋㅋ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='liebe_t',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='당신의 가장 좋아하는 연극 하나만!! 알려주세욯ㅎ??'),
        ),
    ]
