# Generated by Django 2.0.1 on 2018-02-23 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180223_0655'),
        ('accounts', '0013_auto_20180223_1603'),
    ]

    operations = [
    ]
