# Generated by Django 2.0.1 on 2018-02-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20180223_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='경도'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recommand_t',
            field=models.TextField(blank=True, null=True, verbose_name='짧은 자기 소개!'),
        ),
    ]
