# Generated by Django 2.0.1 on 2018-02-24 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0025_auto_20180221_2215'),
        ('accounts', '0015_auto_20180224_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.Theater'),
        ),
    ]
