# Generated by Django 2.0.1 on 2018-02-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_profile_theater'),
        ('accounts', '0014_merge_20180224_2205'),
    ]

    operations = [
    ]
