# Generated by Django 2.0.1 on 2018-02-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_merge_20180225_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='follower', to='accounts.Profile'),
        ),
    ]
