# Generated by Django 2.0.1 on 2018-02-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20180225_1934'),
        ('accounts', '0019_auto_20180226_0304'),
    ]

    operations = [
    ]
