# Generated by Django 2.0.1 on 2018-01-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='minprice',
        ),
    ]
