# Generated by Django 2.0.1 on 2018-01-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_play_minprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='minprice',
            field=models.IntegerField(default=1, verbose_name='최소가격'),
        ),
    ]
