# Generated by Django 2.0.1 on 2018-01-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_play_minprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='grade',
            field=models.IntegerField(default=0, null=True, verbose_name='순위'),
        ),
    ]
