# Generated by Django 2.0.1 on 2018-02-03 08:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Content Of Post'),
        ),
    ]
