# Generated by Django 2.0.1 on 2018-02-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20180203_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(verbose_name='Content Of Post'),
        ),
    ]
