# Generated by Django 2.0.1 on 2018-02-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20180206_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='rate',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=10, verbose_name='평점'),
        ),
        migrations.AddField(
            model_name='review',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='평점'),
        ),
    ]
