# Generated by Django 2.0.1 on 2018-02-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_auto_20180208_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='genre1',
        ),
        migrations.RemoveField(
            model_name='play',
            name='genre2',
        ),
        migrations.DeleteModel(
            name='genre1',
        ),
        migrations.DeleteModel(
            name='genre2',
        ),
    ]
