# Generated by Django 2.0.1 on 2018-02-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_auto_20180208_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='평점'),
        ),
    ]
