# Generated by Django 2.0.1 on 2018-02-15 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_theater'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theater',
        ),
    ]
