# Generated by Django 2.0.1 on 2018-02-17 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0018_auto_20180217_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='theater',
        ),
    ]
