# Generated by Django 2.0.1 on 2018-02-18 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0019_remove_play_theater'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='tomyheart',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
