# Generated by Django 2.0.1 on 2018-02-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0022_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tag',
            field=models.ManyToManyField(related_name='tag_comment', to='search.Tag'),
        ),
    ]
