# Generated by Django 2.0.1 on 2018-02-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0027_auto_20180225_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='poster_self',
            field=models.ImageField(blank=True, null=True, upload_to='poster/%Y/%m/%d', verbose_name='포스터이미지'),
        ),
        migrations.AddField(
            model_name='play',
            name='styurl1_self',
            field=models.ImageField(blank=True, null=True, upload_to='styurl1/%Y/%m/%d', verbose_name='이미지1'),
        ),
        migrations.AddField(
            model_name='play',
            name='styurl2_self',
            field=models.ImageField(blank=True, null=True, upload_to='styurl2/%Y/%m/%d', verbose_name='이미지2'),
        ),
        migrations.AddField(
            model_name='play',
            name='styurl3_self',
            field=models.ImageField(blank=True, null=True, upload_to='styurl3/%Y/%m/%d', verbose_name='이미지3'),
        ),
        migrations.AddField(
            model_name='play',
            name='styurl4_self',
            field=models.ImageField(blank=True, null=True, upload_to='styurl4/%Y/%m/%d', verbose_name='이미지4'),
        ),
    ]
