# Generated by Django 2.0.1 on 2018-02-25 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0028_auto_20180225_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='검증'),
        ),
        migrations.AlterField(
            model_name='play',
            name='name',
            field=models.CharField(max_length=20, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='play',
            name='poster',
            field=models.URLField(blank=True, null=True, verbose_name='포스터이미지경로'),
        ),
        migrations.AlterField(
            model_name='play',
            name='theater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.Theater', verbose_name='극장'),
        ),
        migrations.AlterField(
            model_name='play',
            name='to_my_heart',
            field=models.ManyToManyField(blank=True, null=True, related_name='play_to_my_heart', to=settings.AUTH_USER_MODEL),
        ),
    ]
