# Generated by Django 2.0.1 on 2018-02-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0029_auto_20180225_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='play',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='경도'),
        ),
        migrations.AddField(
            model_name='play',
            name='user_upload',
            field=models.BooleanField(default=False, verbose_name='유저입력'),
        ),
    ]
