# Generated by Django 2.0.1 on 2018-02-27 16:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0032_play_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='play_char',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, '예술적'), (2, '실험적'), (3, '대중적'), (4, 'NTLIVE/해외생중계공연'), (5, '감동적'), (6, '웃음만발'), (7, '아이와 함께'), (8, '어머! 눈감아'), (9, '원작 기반')], max_length=250, null=True, verbose_name='극의 특징'),
        ),
    ]
